services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    environment:
      IP_LIMIT: 10
      IP_LIMIT_DURATION: 1
      API_KEY_LIMIT: 100
      API_KEY_LIMIT_DURATION: 1
      REDIS_ADDRESS: redis:6379
      REDIS_PASSWORD: ""
    depends_on:
      - redis
